var scene = {
    "1000": "首页12宫格及更多",
    "1002": "小程序收藏应用入口，包含朋友tab中的入口",
    "1005": "顶部搜索框的搜索结果页",
    "1007": "单人聊天会话中的小程序消息卡片",
    "1011": "扫描二维码",
    "1014": "小程序模版消息（服务提醒）",
    "1020": "生活号 profile 页相关小程序列表",
    "1023": "系统桌面图标",
    "1037": "小程序打开小程序",
    "1038": "从另一个小程序返回",
    "1090": "长按小程序右上角菜单唤出最近使用历史",
    "1200": "城市服务频道",
    "1201": "芝麻信用频道",
    "1202": "车主服务频道",
    "1203": "医疗服务频道",
    "1204": "大学生活频道",
    "1205": "中小学频道",
    "1206": "共享单车频道",
    "1207": "保险服务频道",
    "1208": "天天有料频道",
    "1209": "支付宝会员频道",
    "1300": "第三方APP（如钉钉）打开",
    "0000": "待确认的场景"
};
var CONFIG = {
    appId: '',
    prefix: 'mtr-',
    mtrVer: '0.0.19',
    stat_share_app: false,
    stat_pull_down_fresh: false,
    stat_page_scroll: false,
    stat_hide: true,
    stat_unload: false,
    stat_reach_bottom: false,
    stat_auto_click: true,
    stat_location: false,
    stat_api: true,
    stat_api_success: true,
    stat_api_long_time: 3000,
    stat_api_fail: true,
    scene: scene
};
export default CONFIG;